### PR TITLE
Switch to AGPLv3

### PR DESCRIPTION
**Pull request by cmccandless**
Unable to update #16 myself to include changes to run require CI on every PR (LICENSE changes were ignored in that PR). Created this PR to include latest changes.

Closes #16 by mutual exclusion

### CODE REVIEW

**Comment by ErikSchierboom** [comment]
@cmccandless I've asked @porkostomus for permission to upgrade the license in https://github.com/exercism/generic-test-runner/pull/16#issuecomment-661736341. If permission is given, we can merge this.

**Comment by cmccandless** [comment]
@ErikSchierboom I think you may have gotten your wires crossed; #16 was not authored by @porkostomus

**Comment by ErikSchierboom** [comment]
@cmccandless I don't think I have, as we are not allowed to change the license without getting approval from [all contributors](https://github.com/exercism/generic-test-runner/graphs/contributors), which includes @porkostomus

**Comment by cmccandless** [comment]
Ah I see... is that all contributors, or all maintainers? How did we manage to change the licenses in the language track repos a few months back? Those repos have many, many contributors who were not asked.

**Comment by iHiD** [comment]
We changed the copyright on the licence file, but not the actual licence itself. The software is licenced by the contributor to exercism under the licence. The actual copyright holder in the licence is sort of irrelevant under MIT. But we didn't really understand this at the time.

**Comment by cmccandless** [comment]
I see. My apologies on the premature merge them. If @porkostomus has an objection to the license change, I will revert the merge.

**Comment by iHiD** [comment]
Thanks @cmccandless :) I believe @porkostomus has 🆗'd other repos, so we should be fine :)

**Comment by ErikSchierboom** [comment]
And @porkostomus has agreed with the change, so we're all good!

**Pull request merged**
