### PR TITLE
Automatically push Docker image to Amazon ECR

### PR DESCRIPTION
**Pull request by ErikSchierboom**
The v3 website uses Docker images from Amazon ECR for all the tooling.
Each tooling repo should have a workflow to automatically push to Amazon ECR whenever something is merged to master.

This PR adds a GitHub Actions workflow to automatically build and push a new Docker image whenever something is merged to master.

See https://github.com/exercism/v3/issues/2728

### CODE REVIEW

**Comment by cmccandless** [comment]
I'm not sure this template repository should be pushing to ECR, but I do agree that this workflow should be included here somehow... Perhaps we can include it and disable it somehow, then add to the instructions for using this repo how to enable it?

**Comment by ErikSchierboom** [comment]
Agreed. @saschamann what would be the best way to disable a workflow?

**Comment by SaschaMann** [comment]
Ask @iHiD to disable actions for this repo: https://github.com/exercism/generic-test-runner/settings/actions

**Comment by cmccandless** [comment]
I'm ok with that. The unit test workflow for `pull_request` doesn't actually run anything important.

**Comment by cmccandless** [comment]
Do we also need to add instructions to https://github.com/exercism/generic-test-runner/blob/master/README.md to ping an admin to add AWS credentials to any new test-runner created from this template?

**Comment by ErikSchierboom** [comment]
That's a good idea.

**Comment by cmccandless** [comment]
@iHiD As mentioned above (https://github.com/exercism/generic-test-runner/pull/21#issuecomment-722435031), we need Github Actions disabled for this repository. Has that been done?

**Comment by iHiD** [comment]
Yes it has.

**Review by cmccandless — APPROVED** [review]

**Comment by cmccandless** [comment]
Thanks @ErikSchierboom @iHiD @SaschaMann

**Comment by iHiD** [comment]
And thank you!

**Pull request merged**
